=== dasheck0/phaser-boilerplate/schemas/scene.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "https://example.com/scene.schema.json",
  "title": "scene",
  "description": "A phaser scene that can be loaded by the phaser boilerplate",
  "type": "object",
  "required": ["groups", "assets", "scenes", "prefabs"],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "assets": {
      "title": "assets",
      "description": "A list of assets that can be used by the scene",
      "type": "array",
      "items": {
        "type": "object",
        "required": ["name", "type", "url"],
        "default": {
          "type": "image",
          "url": ""
        },
        "properties": {
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string",
            "enum": ["image", "plugin", "sceneplugin", "audio", "spritesheet", "script"]
          },
          "url": {
            "type": "string"
          },
          "sceneKey": {
            "type": "string"
          },
          "frameWidth": {
            "type": "integer"
          },
          "frameHeight": {
            "type": "integer"
          },
          "frames": {
            "type": "integer"
          }
        },
        "if": {
          "properties": {
            "type": {
              "enum": ["sceneplugin"]
            }
          }
        },
        "then": {
          "required": ["sceneKey"]
        },
        "else": {
          "if": {
            "properties": {
              "type": {
                "enum": ["spritesheet"]
              }
            }
          },
          "then": {
            "required": ["frameWidth", "frameHeight", "frames"]
          }
        }
      }
    },
    "groups": {
      "title": "groups",
      "description": "A list of groups that can be used to organize assets",
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "scenes": {
      "title": "scenes",
      "description": "A list of scenes, this scene can reference during runtime",
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "prefabs": {
      "type": "object",
      "propertyNames": {
        "type": "string"
      },
      "additionalProperties": {
        "oneOf": [
          {
            "$ref": "basesprite.schema.json"
          },
          {
            "$ref": "baseaudio.schema.json"
          }
        ]
      }
    }
  },
  "additionalProperties": false
}

=== dasheck0/phaser-boilerplate/demo/public/scenes/test.scene.json
{
  "$schema": "../../schemas/scene.schema.json",
  "scenes": [],
  "groups": ["background", "ui", "superui"],
  "assets": [
    {
      "type": "image",
      "name": "sample",
      "url": "images/sample.png"
    }
  ],
  "prefabs": {
    "test": {
      "type": "Test",
      "options": {}
    },
    "pauseButton": {
      "type": "ImageButton",
      "options": {
        "key": "sample",
        "height": {
          "value": 70,
          "relative": false
        },
        "width": {
          "value": 70,
          "relative": false
        },
        "position": {
          "x": 1,
          "y": 0,
          "relative": true
        },
        "anchor": {
          "x": 1,
          "y": 0
        },
        "margin": {
          "top": 16,
          "right": 16
        }
      }
    },
    "panel": {
      "type": "AutoLayout",
      "options": {
        "direction": "vertical",
        "group": "ui",
        "width": {
          "value": 1,
          "relative": true
        },
        "height": {
          "value": 438,
          "relative": false
        },
        "backgroundColor": "#000000",
        "backgroundAlpha": 0.5,
        "anchor": {
          "x": 0,
          "y": 1
        },
        "position": {
          "x": 0,
          "y": 1,
          "relative": true
        },
        "children": [
          {
            "type": "AutoLayout",
            "direction": "horizontal",
            "backgroundColor": "#ff0000",
            "backgroundAlpha": 0.5,
            "children": [
              {
                "type": "ImageButton",
                "key": "sample",
                "maxHeight": 112
              },
              {
                "type": "ImageButton",
                "key": "sample",
                "maxHeight": 112
              },
              {
                "type": "ImageButton",
                "key": "sample",
                "maxHeight": 112
              }
            ]
          },
          {
            "type": "AutoLayout",
            "direction": "horizontal",
            "children": [
              {
                "type": "ImageButton",
                "key": "sample",
                "maxHeight": 112
              },
              {
                "type": "ImageButton",
                "key": "sample",
                "maxHeight": 112
              },
              {
                "type": "ImageButton",
                "key": "sample",
                "maxHeight": 112
              }
            ]
          },
          {
            "type": "AutoLayout",
            "direction": "horizontal",
            "children": [
              {
                "type": "ImageButton",
                "key": "sample",
                "maxHeight": 112
              },
              {
                "type": "ImageButton",
                "key": "sample",
                "maxHeight": 112
              },
              {
                "type": "ImageButton",
                "key": "sample",
                "maxHeight": 112,
                "animation": "tint"
              }
            ]
          }
        ]
      }
    }
  }
}
